# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    json_authenticator:
        class:  AppBundle\Security\JSONAuthenticator
        arguments: ["@security.password_encoder", "@serializer"]
        public: false

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
